from scipy import spatial

def find_buddy(username, users):
    # create own vector
    user_vector = [ users[username][cat] if users[username][cat] else 0 for cat in category_array]
    most_similar_dist = None
    most_similar_username = ''
    for user in users:
        dist = similarity(user_vector, users[user])
        if most_similar_dist == None or dist < most_similar_dist:
            most_similar_dist = dist
            most_similar_username = user
    return most_similar_username


# compute the similarity between another user and 
def similarity(user_vector, other_user_dict):
    # create their vectors
    other_user_vect = [ other_user_dict[cat] if other_user_dict[cat] else 0 for cat in category_array]
    userDistance = spatial.distance.cosine(other_user_vect, user_vector)
    pass


category_array = [
    'Leisure',
    'Sports News',
    'Video Games',
    'Buddhism',
    'Entertainment News',
    'Natural Sciences',
    'Courses',
    'Parenting',
    'Medicine',
    'Improv',
    'Rugby',
    'Film Interviews',
    'Stories for Kids',
    'Visual Arts',
    'Self-Improvement',
    'Careers',
    'Science Fiction',
    'Wilderness',
    'Arts',
    'Business News',
    'Golf',
    'Language Learning',
    'Fashion & Beauty',
    'Film Reviews',
    'Games',
    'TV Reviews',
    'Baseball',
    'Music',
    'Personal Journals',
    'Cricket',
    'Chemistry',
    'Kids & Family',
    'Books',
    'Food',
    'Music History',
    'Stand-Up',
    'Basketball',
    'Outdoor',
    'Games & Hobbies',
    'Documentary',
    'News',
    'Design',
    'Professional',
    'Pets & Animals',
    'Management',
    'Sexuality',
    'Education',
    'Performing Arts',
    'Comedy Interviews',
    'Non-Profit',
    'Crafts',
    'Home & Garden',
    'Places & Travel',
    'Relationships',
    'Judaism',
    'Marketing',
    'News Commentary',
    'TV & Film',
    'Sports',
    'Mathematics',
    'Music Interviews',
    'Tech News',
    'Christianity',
    'Health & Fitness',
    'Government',
    'Wrestling',
    'Religion & Spirituality',
    'Fantasy Sports',
    'Education for Kids',
    'Earth Sciences',
    'Football',
    'Nature',
    'Running',
    'Comedy',
    'Business',
    'Automotive',
    'Social Sciences',
    'Sports & Recreation',
    'Alternative Health',
    'Animation & Manga',
    'Self-Help',
    'Fitness',
    'History',
    'Science',
    'Nutrition',
    'True Crime',
    'Life Sciences',
    'Hobbies',
    'Philosophy',
    'Health',
    'Spirituality',
    'Film History',
    'Hockey',
    'Religion',
    'Volleyball',
    'Soccer',
    'After Shows',
    'Fiction',
    'Drama',
    'Astronomy',
    'Technology',
    'Mental Health',
    'Aviation',
    'Music Commentary',
    'Investing',
    'Society & Culture',
    'Comedy Fiction',
    'Entrepreneurship',
    'How To',
    'Islam'
]